# SPDX-License-Identifier: GPL-2.0-only
# SPDX-FileCopyrightText: Copyright (c) 2025, NVIDIA CORPORATION & AFFILIATES.  All rights reserved.

DTC_FLAGS += -@

old-dtb := $(dtb-y)
old-dtbo := $(dtbo-y)
dtb-y :=
dtbo-y :=
makefile-path := t264/nv-public/overlay

dtbo-y += tegra264-ftpm.dtbo
dtbo-y += tegra264-p3971-camera-dual-hawk-ar0234-p3762-overlay.dtbo
dtbo-y += tegra264-p3971-camera-dual-imx274-overlay.dtbo
dtbo-y += tegra264-p3971-camera-eCAM130A-overlay.dtbo
dtbo-y += tegra264-p3971-camera-e3331-overlay.dtbo
dtbo-y += tegra264-p3971-camera-e3333-overlay.dtbo
dtbo-y += tegra264-p3971-camera-imx185-overlay.dtbo
dtbo-y += tegra264-p3971-camera-imx390-overlay.dtbo
dtbo-y += tegra264-p3971-camera-imx390-addr-0x21-overlay.dtbo
dtbo-y += tegra264-p3971-camera-p3762-a00-1Hawk-overlay.dtbo
dtbo-y += tegra264-p3971-camera-p3762-a00-2Hawk-overlay.dtbo
dtbo-y += tegra264-p3971-camera-p3762-a00-3Hawk-3Owl-overlay.dtbo
dtbo-y += tegra264-p3971-camera-p3762-a00-4Hawk-overlay.dtbo
dtbo-y += tegra264-p3971-camera-p3762-a00-4Owl-overlay.dtbo
dtbo-y += tegra264-p3971-camera-p3762-a00-overlay.dtbo

dtbo-y += tegra264-p3971-camera-fr_fpa_4a_agx-overlay.dtbo
dtbo-y += tegra264-p3971-camera-fr_fpa_4a_txa-overlay.dtbo

dtbo-y += tegra264-p3971-camera-fr_imx283-j5-4lane-overlay.dtbo
dtbo-y += tegra264-p3971-camera-fr_imx283-j6-4lane-overlay.dtbo
dtbo-y += tegra264-p3971-camera-fr_imx283-j7-4lane-overlay.dtbo
dtbo-y += tegra264-p3971-camera-fr_imx283-j8-4lane-overlay.dtbo

dtbo-y += tegra264-p3971-camera-fr_imx296-j5-1lane-overlay.dtbo
dtbo-y += tegra264-p3971-camera-fr_imx296-j6-1lane-overlay.dtbo
dtbo-y += tegra264-p3971-camera-fr_imx296-j7-1lane-overlay.dtbo
dtbo-y += tegra264-p3971-camera-fr_imx296-j8-1lane-overlay.dtbo

dtbo-y += tegra264-p3971-camera-fr_imx304-j5-4lane-overlay.dtbo
dtbo-y += tegra264-p3971-camera-fr_imx304-j6-4lane-overlay.dtbo
dtbo-y += tegra264-p3971-camera-fr_imx304-j7-4lane-overlay.dtbo
dtbo-y += tegra264-p3971-camera-fr_imx304-j8-4lane-overlay.dtbo

dtbo-y += tegra264-p3971-camera-fr_imx335-j5-2lane-overlay.dtbo
dtbo-y += tegra264-p3971-camera-fr_imx335-j5-4lane-overlay.dtbo
dtbo-y += tegra264-p3971-camera-fr_imx335-j6-2lane-overlay.dtbo
dtbo-y += tegra264-p3971-camera-fr_imx335-j6-4lane-overlay.dtbo
dtbo-y += tegra264-p3971-camera-fr_imx335-j7-2lane-overlay.dtbo
dtbo-y += tegra264-p3971-camera-fr_imx335-j7-4lane-overlay.dtbo
dtbo-y += tegra264-p3971-camera-fr_imx335-j8-2lane-overlay.dtbo
dtbo-y += tegra264-p3971-camera-fr_imx335-j8-4lane-overlay.dtbo

dtbo-y += tegra264-p3971-camera-fr_imx412-j5-2lane-overlay.dtbo
dtbo-y += tegra264-p3971-camera-fr_imx412-j5-4lane-overlay.dtbo
dtbo-y += tegra264-p3971-camera-fr_imx412-j6-2lane-overlay.dtbo
dtbo-y += tegra264-p3971-camera-fr_imx412-j6-4lane-overlay.dtbo
dtbo-y += tegra264-p3971-camera-fr_imx412-j7-2lane-overlay.dtbo
dtbo-y += tegra264-p3971-camera-fr_imx412-j7-4lane-overlay.dtbo
dtbo-y += tegra264-p3971-camera-fr_imx412-j8-2lane-overlay.dtbo
dtbo-y += tegra264-p3971-camera-fr_imx412-j8-4lane-overlay.dtbo

dtbo-y += tegra264-p3971-camera-fr_imx464-j5-2lane-overlay.dtbo
dtbo-y += tegra264-p3971-camera-fr_imx464-j5-4lane-overlay.dtbo
dtbo-y += tegra264-p3971-camera-fr_imx464-j6-2lane-overlay.dtbo
dtbo-y += tegra264-p3971-camera-fr_imx464-j6-4lane-overlay.dtbo
dtbo-y += tegra264-p3971-camera-fr_imx464-j7-2lane-overlay.dtbo
dtbo-y += tegra264-p3971-camera-fr_imx464-j7-4lane-overlay.dtbo
dtbo-y += tegra264-p3971-camera-fr_imx464-j8-2lane-overlay.dtbo
dtbo-y += tegra264-p3971-camera-fr_imx464-j8-4lane-overlay.dtbo

dtbo-y += tegra264-p3971-camera-fr_imx530-j5-4lane-overlay.dtbo
dtbo-y += tegra264-p3971-camera-fr_imx530-j6-4lane-overlay.dtbo
dtbo-y += tegra264-p3971-camera-fr_imx530-j7-4lane-overlay.dtbo
dtbo-y += tegra264-p3971-camera-fr_imx530-j8-4lane-overlay.dtbo

dtbo-y += tegra264-p3971-camera-fr_imx565-j5-2lane-overlay.dtbo
dtbo-y += tegra264-p3971-camera-fr_imx565-j5-4lane-overlay.dtbo
dtbo-y += tegra264-p3971-camera-fr_imx565-j6-2lane-overlay.dtbo
dtbo-y += tegra264-p3971-camera-fr_imx565-j6-4lane-overlay.dtbo
dtbo-y += tegra264-p3971-camera-fr_imx565-j7-2lane-overlay.dtbo
dtbo-y += tegra264-p3971-camera-fr_imx565-j7-4lane-overlay.dtbo
dtbo-y += tegra264-p3971-camera-fr_imx565-j8-2lane-overlay.dtbo
dtbo-y += tegra264-p3971-camera-fr_imx565-j8-4lane-overlay.dtbo

dtbo-y += tegra264-p3971-camera-fr_imx568-j5-2lane-overlay.dtbo
dtbo-y += tegra264-p3971-camera-fr_imx568-j5-4lane-overlay.dtbo
dtbo-y += tegra264-p3971-camera-fr_imx568-j6-2lane-overlay.dtbo
dtbo-y += tegra264-p3971-camera-fr_imx568-j6-4lane-overlay.dtbo
dtbo-y += tegra264-p3971-camera-fr_imx568-j7-2lane-overlay.dtbo
dtbo-y += tegra264-p3971-camera-fr_imx568-j7-4lane-overlay.dtbo
dtbo-y += tegra264-p3971-camera-fr_imx568-j8-2lane-overlay.dtbo
dtbo-y += tegra264-p3971-camera-fr_imx568-j8-4lane-overlay.dtbo

dtbo-y += tegra264-p3971-camera-fr_imx577-j5-2lane-overlay.dtbo
dtbo-y += tegra264-p3971-camera-fr_imx577-j5-4lane-overlay.dtbo
dtbo-y += tegra264-p3971-camera-fr_imx577-j6-2lane-overlay.dtbo
dtbo-y += tegra264-p3971-camera-fr_imx577-j6-4lane-overlay.dtbo
dtbo-y += tegra264-p3971-camera-fr_imx577-j7-2lane-overlay.dtbo
dtbo-y += tegra264-p3971-camera-fr_imx577-j7-4lane-overlay.dtbo
dtbo-y += tegra264-p3971-camera-fr_imx577-j8-2lane-overlay.dtbo
dtbo-y += tegra264-p3971-camera-fr_imx577-j8-4lane-overlay.dtbo

dtbo-y += tegra264-p3971-camera-fr_imx585-j5-2lane-overlay.dtbo
dtbo-y += tegra264-p3971-camera-fr_imx585-j5-4lane-overlay.dtbo
dtbo-y += tegra264-p3971-camera-fr_imx585-j6-2lane-overlay.dtbo
dtbo-y += tegra264-p3971-camera-fr_imx585-j6-4lane-overlay.dtbo
dtbo-y += tegra264-p3971-camera-fr_imx585-j7-2lane-overlay.dtbo
dtbo-y += tegra264-p3971-camera-fr_imx585-j7-4lane-overlay.dtbo
dtbo-y += tegra264-p3971-camera-fr_imx585-j8-2lane-overlay.dtbo
dtbo-y += tegra264-p3971-camera-fr_imx585-j8-4lane-overlay.dtbo

dtbo-y += tegra264-p3971-camera-fr_imx636-j5-4lane-overlay.dtbo
dtbo-y += tegra264-p3971-camera-fr_imx636-j6-4lane-overlay.dtbo
dtbo-y += tegra264-p3971-camera-fr_imx636-j7-4lane-overlay.dtbo
dtbo-y += tegra264-p3971-camera-fr_imx636-j8-4lane-overlay.dtbo

dtbo-y += tegra264-p3971-camera-fr_imx662-j5-2lane-overlay.dtbo
dtbo-y += tegra264-p3971-camera-fr_imx662-j5-4lane-overlay.dtbo
dtbo-y += tegra264-p3971-camera-fr_imx662-j6-2lane-overlay.dtbo
dtbo-y += tegra264-p3971-camera-fr_imx662-j6-4lane-overlay.dtbo
dtbo-y += tegra264-p3971-camera-fr_imx662-j7-2lane-overlay.dtbo
dtbo-y += tegra264-p3971-camera-fr_imx662-j7-4lane-overlay.dtbo
dtbo-y += tegra264-p3971-camera-fr_imx662-j8-2lane-overlay.dtbo
dtbo-y += tegra264-p3971-camera-fr_imx662-j8-4lane-overlay.dtbo

dtbo-y += tegra264-p3971-camera-fr_imx675-j5-2lane-overlay.dtbo
dtbo-y += tegra264-p3971-camera-fr_imx675-j5-4lane-overlay.dtbo
dtbo-y += tegra264-p3971-camera-fr_imx675-j6-2lane-overlay.dtbo
dtbo-y += tegra264-p3971-camera-fr_imx675-j6-4lane-overlay.dtbo
dtbo-y += tegra264-p3971-camera-fr_imx675-j7-2lane-overlay.dtbo
dtbo-y += tegra264-p3971-camera-fr_imx675-j7-4lane-overlay.dtbo
dtbo-y += tegra264-p3971-camera-fr_imx675-j8-2lane-overlay.dtbo
dtbo-y += tegra264-p3971-camera-fr_imx675-j8-4lane-overlay.dtbo

dtbo-y += tegra264-p3971-camera-fr_imx676-j5-2lane-overlay.dtbo
dtbo-y += tegra264-p3971-camera-fr_imx676-j5-4lane-overlay.dtbo
dtbo-y += tegra264-p3971-camera-fr_imx676-j6-2lane-overlay.dtbo
dtbo-y += tegra264-p3971-camera-fr_imx676-j6-4lane-overlay.dtbo
dtbo-y += tegra264-p3971-camera-fr_imx676-j7-2lane-overlay.dtbo
dtbo-y += tegra264-p3971-camera-fr_imx676-j7-4lane-overlay.dtbo
dtbo-y += tegra264-p3971-camera-fr_imx676-j8-2lane-overlay.dtbo
dtbo-y += tegra264-p3971-camera-fr_imx676-j8-4lane-overlay.dtbo

dtbo-y += tegra264-p3971-camera-fr_imx678-j5-2lane-overlay.dtbo
dtbo-y += tegra264-p3971-camera-fr_imx678-j5-4lane-overlay.dtbo
dtbo-y += tegra264-p3971-camera-fr_imx678-j6-2lane-overlay.dtbo
dtbo-y += tegra264-p3971-camera-fr_imx678-j6-4lane-overlay.dtbo
dtbo-y += tegra264-p3971-camera-fr_imx678-j7-2lane-overlay.dtbo
dtbo-y += tegra264-p3971-camera-fr_imx678-j7-4lane-overlay.dtbo
dtbo-y += tegra264-p3971-camera-fr_imx678-j8-2lane-overlay.dtbo
dtbo-y += tegra264-p3971-camera-fr_imx678-j8-4lane-overlay.dtbo

dtbo-y += tegra264-p3971-camera-fr_imx715-j5-2lane-overlay.dtbo
dtbo-y += tegra264-p3971-camera-fr_imx715-j5-4lane-overlay.dtbo
dtbo-y += tegra264-p3971-camera-fr_imx715-j6-2lane-overlay.dtbo
dtbo-y += tegra264-p3971-camera-fr_imx715-j6-4lane-overlay.dtbo
dtbo-y += tegra264-p3971-camera-fr_imx715-j7-2lane-overlay.dtbo
dtbo-y += tegra264-p3971-camera-fr_imx715-j7-4lane-overlay.dtbo
dtbo-y += tegra264-p3971-camera-fr_imx715-j8-2lane-overlay.dtbo
dtbo-y += tegra264-p3971-camera-fr_imx715-j8-4lane-overlay.dtbo

dtbo-y += tegra264-p3971-camera-fr_imx838-j5-2lane-overlay.dtbo
dtbo-y += tegra264-p3971-camera-fr_imx838-j5-4lane-overlay.dtbo
dtbo-y += tegra264-p3971-camera-fr_imx838-j6-2lane-overlay.dtbo
dtbo-y += tegra264-p3971-camera-fr_imx838-j6-4lane-overlay.dtbo
dtbo-y += tegra264-p3971-camera-fr_imx838-j7-2lane-overlay.dtbo
dtbo-y += tegra264-p3971-camera-fr_imx838-j7-4lane-overlay.dtbo
dtbo-y += tegra264-p3971-camera-fr_imx838-j8-2lane-overlay.dtbo
dtbo-y += tegra264-p3971-camera-fr_imx838-j8-4lane-overlay.dtbo

dtbo-y += tegra264-p3971-camera-fr_imx900-j5-1lane-overlay.dtbo
dtbo-y += tegra264-p3971-camera-fr_imx900-j5-2lane-overlay.dtbo
dtbo-y += tegra264-p3971-camera-fr_imx900-j5-4lane-overlay.dtbo
dtbo-y += tegra264-p3971-camera-fr_imx900-j6-1lane-overlay.dtbo
dtbo-y += tegra264-p3971-camera-fr_imx900-j6-2lane-overlay.dtbo
dtbo-y += tegra264-p3971-camera-fr_imx900-j6-4lane-overlay.dtbo
dtbo-y += tegra264-p3971-camera-fr_imx900-j7-1lane-overlay.dtbo
dtbo-y += tegra264-p3971-camera-fr_imx900-j7-2lane-overlay.dtbo
dtbo-y += tegra264-p3971-camera-fr_imx900-j7-4lane-overlay.dtbo
dtbo-y += tegra264-p3971-camera-fr_imx900-j8-1lane-overlay.dtbo
dtbo-y += tegra264-p3971-camera-fr_imx900-j8-2lane-overlay.dtbo
dtbo-y += tegra264-p3971-camera-fr_imx900-j8-4lane-overlay.dtbo

dtbo-y += tegra264-p3971-camera-fr_j5-gmsl-overlay.dtbo
dtbo-y += tegra264-p3971-camera-fr_j6-gmsl-overlay.dtbo
dtbo-y += tegra264-p3971-camera-fr_j7-gmsl-overlay.dtbo
dtbo-y += tegra264-p3971-camera-fr_j8-gmsl-overlay.dtbo

ifneq ($(dtb-y),)
dtb-y := $(addprefix $(makefile-path)/,$(dtb-y))
endif
ifneq ($(dtbo-y),)
dtbo-y := $(addprefix $(makefile-path)/,$(dtbo-y))
endif

dtb-y += $(old-dtb)
dtbo-y += $(old-dtbo)

