# SPDX-License-Identifier: GPL-2.0-only
# SPDX-FileCopyrightText: Copyright (c) 2023, NVIDIA CORPORATION & AFFILIATES.  All rights reserved.

DTC_FLAGS += -@

old-dtb := $(dtb-y)
old-dtbo := $(dtbo-y)
dtb-y :=
dtbo-y :=
makefile-path := t23x/nv-public/overlay

dtbo-y += tegra-optee.dtbo
dtbo-y += tegra234-audio-overlay.dtbo
dtbo-y += tegra234-carveouts.dtbo
dtbo-y += tegra234-dcb-p3767-0000-hdmi.dtbo
dtbo-y += tegra234-jetson.dtbo
dtbo-y += tegra234-p3737-0000+p3701-0000-as-p3701-0004.dtbo
dtbo-y += tegra234-p3737-0000+p3701-0000-as-p3767-0000.dtbo
dtbo-y += tegra234-p3737-0000+p3701-0000-as-p3767-0001.dtbo
dtbo-y += tegra234-p3737-0000+p3701-0000-as-p3767-0003.dtbo
dtbo-y += tegra234-p3737-0000+p3701-0000-as-p3767-0004.dtbo
dtbo-y += tegra234-p3737-0000+p3701-0000-dynamic.dtbo
dtbo-y += tegra234-p3768-0000+p3767-0000-dynamic.dtbo
dtbo-y += tegra234-p3737-0000+p3701-0000-audio-adafruit-uda1334a.dtbo
dtbo-y += tegra234-p3737-0000+p3701-0000-audio-adafruit-sph0645lm4h.dtbo
dtbo-y += tegra234-p3737-0000+p3701-0000-audio-fe-pi.dtbo
dtbo-y += tegra234-p3737-0000+p3701-0000-audio-respeaker-4-mic-array.dtbo
dtbo-y += tegra234-p3737-0000+p3701-0000-audio-respeaker-4-mic-lin-array.dtbo
dtbo-y += tegra234-p3737-0000+p3701-0000-csi.dtbo
dtbo-y += tegra234-p3737-0000+p3701-0000-hdr40.dtbo
dtbo-y += tegra234-p3737-0000+p3701-0000-m2ke.dtbo
dtbo-y += tegra234-p3767-0000+p3509-a02-audio-adafruit-sph0645lm4h.dtbo
dtbo-y += tegra234-p3767-0000+p3509-a02-audio-adafruit-uda1334a.dtbo
dtbo-y += tegra234-p3767-0000+p3509-a02-audio-fe-pi.dtbo
dtbo-y += tegra234-p3767-0000+p3509-a02-audio-respeaker-4-mic-array.dtbo
dtbo-y += tegra234-p3767-0000+p3509-a02-audio-respeaker-4-mic-lin-array.dtbo
dtbo-y += tegra234-p3767-0000+p3509-a02-csi.dtbo
dtbo-y += tegra234-p3767-0000+p3509-a02-hdr40.dtbo
dtbo-y += tegra234-p3767-0000+p3509-a02-m2ke.dtbo
dtbo-y += tegra234-p3767-0000+p3768-0000-csi.dtbo
dtbo-y += tegra234-p3740-0002+p3701-0008-hdr20.dtbo
dtbo-y += tegra234-p3740-0002+p3701-0008-m2ke.dtbo
dtbo-y += tegra234-p3740-0002+p3701-0008-m2kb.dtbo
dtbo-y += tegra234-p3740-0002-p3701-0008-csi.dtbo
dtbo-y += tegra234-p3737-camera-dual-imx274-overlay.dtbo
dtbo-y += tegra234-p3737-camera-e3331-overlay.dtbo
dtbo-y += tegra234-p3737-camera-e3333-overlay.dtbo
dtbo-y += tegra234-p3737-camera-imx185-overlay.dtbo
dtbo-y += tegra234-p3767-camera-p3768-imx219-dual.dtbo
dtbo-y += tegra234-p3767-camera-p3768-imx477-dual.dtbo
dtbo-y += tegra234-p3767-camera-p3768-imx477-dual-4lane.dtbo
dtbo-y += tegra234-p3767-camera-p3768-imx477-imx219.dtbo
dtbo-y += tegra234-p3737-camera-eCAM130A-overlay.dtbo
dtbo-y += tegra234-p3737-camera-dual-hawk-ar0234-e3653-overlay.dtbo
dtbo-y += tegra234-p3737-camera-imx390-overlay.dtbo
dtbo-y += tegra234-p3737-camera-p3762-a00-overlay.dtbo
dtbo-y += tegra234-p3740-camera-p3783-a00-overlay.dtbo
dtbo-y += tegra234-p3767-camera-p3768-imx219-C.dtbo
dtbo-y += tegra234-p3767-camera-p3768-imx219-A.dtbo
dtbo-y += tegra234-p3767-camera-p3768-imx219-imx477.dtbo
dtbo-y += tegra234-p3767-camera-p3768-imx477-C.dtbo
dtbo-y += tegra234-p3767-camera-p3768-imx477-A.dtbo


dtbo-y += tegra234-p3737-camera-fr_fpa_4a_agx-overlay.dtbo
dtbo-y += tegra234-p3737-camera-fr_fpa_4a_txa-overlay.dtbo

dtbo-y += tegra234-p3737-camera-fr_imx296-j5-1lane-overlay.dtbo
dtbo-y += tegra234-p3737-camera-fr_imx296-j6-1lane-overlay.dtbo
dtbo-y += tegra234-p3737-camera-fr_imx296-j7-1lane-overlay.dtbo
dtbo-y += tegra234-p3737-camera-fr_imx296-j8-1lane-overlay.dtbo

dtbo-y += tegra234-p3737-camera-fr_imx304-j5-4lane-overlay.dtbo
dtbo-y += tegra234-p3737-camera-fr_imx304-j6-4lane-overlay.dtbo
dtbo-y += tegra234-p3737-camera-fr_imx304-j7-4lane-overlay.dtbo
dtbo-y += tegra234-p3737-camera-fr_imx304-j8-4lane-overlay.dtbo

dtbo-y += tegra234-p3737-camera-fr_imx335-j5-2lane-overlay.dtbo
dtbo-y += tegra234-p3737-camera-fr_imx335-j5-4lane-overlay.dtbo
dtbo-y += tegra234-p3737-camera-fr_imx335-j6-2lane-overlay.dtbo
dtbo-y += tegra234-p3737-camera-fr_imx335-j6-4lane-overlay.dtbo
dtbo-y += tegra234-p3737-camera-fr_imx335-j7-2lane-overlay.dtbo
dtbo-y += tegra234-p3737-camera-fr_imx335-j7-4lane-overlay.dtbo
dtbo-y += tegra234-p3737-camera-fr_imx335-j8-2lane-overlay.dtbo
dtbo-y += tegra234-p3737-camera-fr_imx335-j8-4lane-overlay.dtbo

dtbo-y += tegra234-p3737-camera-fr_imx412-j5-2lane-overlay.dtbo
dtbo-y += tegra234-p3737-camera-fr_imx412-j5-4lane-overlay.dtbo
dtbo-y += tegra234-p3737-camera-fr_imx412-j6-2lane-overlay.dtbo
dtbo-y += tegra234-p3737-camera-fr_imx412-j6-4lane-overlay.dtbo
dtbo-y += tegra234-p3737-camera-fr_imx412-j7-2lane-overlay.dtbo
dtbo-y += tegra234-p3737-camera-fr_imx412-j7-4lane-overlay.dtbo
dtbo-y += tegra234-p3737-camera-fr_imx412-j8-2lane-overlay.dtbo
dtbo-y += tegra234-p3737-camera-fr_imx412-j8-4lane-overlay.dtbo

dtbo-y += tegra234-p3737-camera-fr_imx464-j5-2lane-overlay.dtbo
dtbo-y += tegra234-p3737-camera-fr_imx464-j5-4lane-overlay.dtbo
dtbo-y += tegra234-p3737-camera-fr_imx464-j6-2lane-overlay.dtbo
dtbo-y += tegra234-p3737-camera-fr_imx464-j6-4lane-overlay.dtbo
dtbo-y += tegra234-p3737-camera-fr_imx464-j7-2lane-overlay.dtbo
dtbo-y += tegra234-p3737-camera-fr_imx464-j7-4lane-overlay.dtbo
dtbo-y += tegra234-p3737-camera-fr_imx464-j8-2lane-overlay.dtbo
dtbo-y += tegra234-p3737-camera-fr_imx464-j8-4lane-overlay.dtbo

dtbo-y += tegra234-p3737-camera-fr_imx530-j5-4lane-overlay.dtbo
dtbo-y += tegra234-p3737-camera-fr_imx530-j6-4lane-overlay.dtbo
dtbo-y += tegra234-p3737-camera-fr_imx530-j7-4lane-overlay.dtbo
dtbo-y += tegra234-p3737-camera-fr_imx530-j8-4lane-overlay.dtbo

dtbo-y += tegra234-p3737-camera-fr_imx565-j5-2lane-overlay.dtbo
dtbo-y += tegra234-p3737-camera-fr_imx565-j5-4lane-overlay.dtbo
dtbo-y += tegra234-p3737-camera-fr_imx565-j6-2lane-overlay.dtbo
dtbo-y += tegra234-p3737-camera-fr_imx565-j6-4lane-overlay.dtbo
dtbo-y += tegra234-p3737-camera-fr_imx565-j7-2lane-overlay.dtbo
dtbo-y += tegra234-p3737-camera-fr_imx565-j7-4lane-overlay.dtbo
dtbo-y += tegra234-p3737-camera-fr_imx565-j8-2lane-overlay.dtbo
dtbo-y += tegra234-p3737-camera-fr_imx565-j8-4lane-overlay.dtbo

dtbo-y += tegra234-p3737-camera-fr_imx568-j5-2lane-overlay.dtbo
dtbo-y += tegra234-p3737-camera-fr_imx568-j5-4lane-overlay.dtbo
dtbo-y += tegra234-p3737-camera-fr_imx568-j6-2lane-overlay.dtbo
dtbo-y += tegra234-p3737-camera-fr_imx568-j6-4lane-overlay.dtbo
dtbo-y += tegra234-p3737-camera-fr_imx568-j7-2lane-overlay.dtbo
dtbo-y += tegra234-p3737-camera-fr_imx568-j7-4lane-overlay.dtbo
dtbo-y += tegra234-p3737-camera-fr_imx568-j8-2lane-overlay.dtbo
dtbo-y += tegra234-p3737-camera-fr_imx568-j8-4lane-overlay.dtbo

dtbo-y += tegra234-p3737-camera-fr_imx577-j5-2lane-overlay.dtbo
dtbo-y += tegra234-p3737-camera-fr_imx577-j5-4lane-overlay.dtbo
dtbo-y += tegra234-p3737-camera-fr_imx577-j6-2lane-overlay.dtbo
dtbo-y += tegra234-p3737-camera-fr_imx577-j6-4lane-overlay.dtbo
dtbo-y += tegra234-p3737-camera-fr_imx577-j7-2lane-overlay.dtbo
dtbo-y += tegra234-p3737-camera-fr_imx577-j7-4lane-overlay.dtbo
dtbo-y += tegra234-p3737-camera-fr_imx577-j8-2lane-overlay.dtbo
dtbo-y += tegra234-p3737-camera-fr_imx577-j8-4lane-overlay.dtbo

dtbo-y += tegra234-p3737-camera-fr_imx585-j5-2lane-overlay.dtbo
dtbo-y += tegra234-p3737-camera-fr_imx585-j5-4lane-overlay.dtbo
dtbo-y += tegra234-p3737-camera-fr_imx585-j6-2lane-overlay.dtbo
dtbo-y += tegra234-p3737-camera-fr_imx585-j6-4lane-overlay.dtbo
dtbo-y += tegra234-p3737-camera-fr_imx585-j7-2lane-overlay.dtbo
dtbo-y += tegra234-p3737-camera-fr_imx585-j7-4lane-overlay.dtbo
dtbo-y += tegra234-p3737-camera-fr_imx585-j8-2lane-overlay.dtbo
dtbo-y += tegra234-p3737-camera-fr_imx585-j8-4lane-overlay.dtbo

dtbo-y += tegra234-p3737-camera-fr_imx636-j5-4lane-overlay.dtbo
dtbo-y += tegra234-p3737-camera-fr_imx636-j6-4lane-overlay.dtbo
dtbo-y += tegra234-p3737-camera-fr_imx636-j7-4lane-overlay.dtbo
dtbo-y += tegra234-p3737-camera-fr_imx636-j8-4lane-overlay.dtbo

dtbo-y += tegra234-p3737-camera-fr_imx662-j5-2lane-overlay.dtbo
dtbo-y += tegra234-p3737-camera-fr_imx662-j5-4lane-overlay.dtbo
dtbo-y += tegra234-p3737-camera-fr_imx662-j6-2lane-overlay.dtbo
dtbo-y += tegra234-p3737-camera-fr_imx662-j6-4lane-overlay.dtbo
dtbo-y += tegra234-p3737-camera-fr_imx662-j7-2lane-overlay.dtbo
dtbo-y += tegra234-p3737-camera-fr_imx662-j7-4lane-overlay.dtbo
dtbo-y += tegra234-p3737-camera-fr_imx662-j8-2lane-overlay.dtbo
dtbo-y += tegra234-p3737-camera-fr_imx662-j8-4lane-overlay.dtbo

dtbo-y += tegra234-p3737-camera-fr_imx675-j5-2lane-overlay.dtbo
dtbo-y += tegra234-p3737-camera-fr_imx675-j5-4lane-overlay.dtbo
dtbo-y += tegra234-p3737-camera-fr_imx675-j6-2lane-overlay.dtbo
dtbo-y += tegra234-p3737-camera-fr_imx675-j6-4lane-overlay.dtbo
dtbo-y += tegra234-p3737-camera-fr_imx675-j7-2lane-overlay.dtbo
dtbo-y += tegra234-p3737-camera-fr_imx675-j7-4lane-overlay.dtbo
dtbo-y += tegra234-p3737-camera-fr_imx675-j8-2lane-overlay.dtbo
dtbo-y += tegra234-p3737-camera-fr_imx675-j8-4lane-overlay.dtbo

dtbo-y += tegra234-p3737-camera-fr_imx676-j5-2lane-overlay.dtbo
dtbo-y += tegra234-p3737-camera-fr_imx676-j5-4lane-overlay.dtbo
dtbo-y += tegra234-p3737-camera-fr_imx676-j6-2lane-overlay.dtbo
dtbo-y += tegra234-p3737-camera-fr_imx676-j6-4lane-overlay.dtbo
dtbo-y += tegra234-p3737-camera-fr_imx676-j7-2lane-overlay.dtbo
dtbo-y += tegra234-p3737-camera-fr_imx676-j7-4lane-overlay.dtbo
dtbo-y += tegra234-p3737-camera-fr_imx676-j8-2lane-overlay.dtbo
dtbo-y += tegra234-p3737-camera-fr_imx676-j8-4lane-overlay.dtbo

dtbo-y += tegra234-p3737-camera-fr_imx678-j5-2lane-overlay.dtbo
dtbo-y += tegra234-p3737-camera-fr_imx678-j5-4lane-overlay.dtbo
dtbo-y += tegra234-p3737-camera-fr_imx678-j6-2lane-overlay.dtbo
dtbo-y += tegra234-p3737-camera-fr_imx678-j6-4lane-overlay.dtbo
dtbo-y += tegra234-p3737-camera-fr_imx678-j7-2lane-overlay.dtbo
dtbo-y += tegra234-p3737-camera-fr_imx678-j7-4lane-overlay.dtbo
dtbo-y += tegra234-p3737-camera-fr_imx678-j8-2lane-overlay.dtbo
dtbo-y += tegra234-p3737-camera-fr_imx678-j8-4lane-overlay.dtbo

dtbo-y += tegra234-p3737-camera-fr_imx715-j5-2lane-overlay.dtbo
dtbo-y += tegra234-p3737-camera-fr_imx715-j5-4lane-overlay.dtbo
dtbo-y += tegra234-p3737-camera-fr_imx715-j6-2lane-overlay.dtbo
dtbo-y += tegra234-p3737-camera-fr_imx715-j6-4lane-overlay.dtbo
dtbo-y += tegra234-p3737-camera-fr_imx715-j7-2lane-overlay.dtbo
dtbo-y += tegra234-p3737-camera-fr_imx715-j7-4lane-overlay.dtbo
dtbo-y += tegra234-p3737-camera-fr_imx715-j8-2lane-overlay.dtbo
dtbo-y += tegra234-p3737-camera-fr_imx715-j8-4lane-overlay.dtbo

dtbo-y += tegra234-p3737-camera-fr_imx900-j5-1lane-overlay.dtbo
dtbo-y += tegra234-p3737-camera-fr_imx900-j5-2lane-overlay.dtbo
dtbo-y += tegra234-p3737-camera-fr_imx900-j5-4lane-overlay.dtbo
dtbo-y += tegra234-p3737-camera-fr_imx900-j6-1lane-overlay.dtbo
dtbo-y += tegra234-p3737-camera-fr_imx900-j6-2lane-overlay.dtbo
dtbo-y += tegra234-p3737-camera-fr_imx900-j6-4lane-overlay.dtbo
dtbo-y += tegra234-p3737-camera-fr_imx900-j7-1lane-overlay.dtbo
dtbo-y += tegra234-p3737-camera-fr_imx900-j7-2lane-overlay.dtbo
dtbo-y += tegra234-p3737-camera-fr_imx900-j7-4lane-overlay.dtbo
dtbo-y += tegra234-p3737-camera-fr_imx900-j8-1lane-overlay.dtbo
dtbo-y += tegra234-p3737-camera-fr_imx900-j8-2lane-overlay.dtbo
dtbo-y += tegra234-p3737-camera-fr_imx900-j8-4lane-overlay.dtbo

dtbo-y += tegra234-p3737-camera-fr_j5-gmsl-overlay.dtbo
dtbo-y += tegra234-p3737-camera-fr_j6-gmsl-overlay.dtbo
dtbo-y += tegra234-p3737-camera-fr_j7-gmsl-overlay.dtbo
dtbo-y += tegra234-p3737-camera-fr_j8-gmsl-overlay.dtbo

dtbo-y += tegra234-p3767-camera-p3768-fr_fpa_a_p22-overlay.dtbo

dtbo-y += tegra234-p3767-camera-p3768-fr_imx296-cam0-1lane-overlay.dtbo
dtbo-y += tegra234-p3767-camera-p3768-fr_imx296-cam1-1lane-overlay.dtbo

dtbo-y += tegra234-p3767-camera-p3768-fr_imx335-cam0-2lane-overlay.dtbo
dtbo-y += tegra234-p3767-camera-p3768-fr_imx335-cam1-2lane-overlay.dtbo
dtbo-y += tegra234-p3767-camera-p3768-fr_imx335-cam1-4lane-overlay.dtbo

dtbo-y += tegra234-p3767-camera-p3768-fr_imx412-cam0-2lane-overlay.dtbo
dtbo-y += tegra234-p3767-camera-p3768-fr_imx412-cam1-2lane-overlay.dtbo
dtbo-y += tegra234-p3767-camera-p3768-fr_imx412-cam1-4lane-overlay.dtbo

dtbo-y += tegra234-p3767-camera-p3768-fr_imx464-cam0-2lane-overlay.dtbo
dtbo-y += tegra234-p3767-camera-p3768-fr_imx464-cam1-2lane-overlay.dtbo
dtbo-y += tegra234-p3767-camera-p3768-fr_imx464-cam1-4lane-overlay.dtbo

dtbo-y += tegra234-p3767-camera-p3768-fr_imx565-cam0-2lane-overlay.dtbo
dtbo-y += tegra234-p3767-camera-p3768-fr_imx565-cam1-2lane-overlay.dtbo
dtbo-y += tegra234-p3767-camera-p3768-fr_imx565-cam1-4lane-overlay.dtbo

dtbo-y += tegra234-p3767-camera-p3768-fr_imx568-cam0-2lane-overlay.dtbo
dtbo-y += tegra234-p3767-camera-p3768-fr_imx568-cam1-2lane-overlay.dtbo
dtbo-y += tegra234-p3767-camera-p3768-fr_imx568-cam1-4lane-overlay.dtbo

dtbo-y += tegra234-p3767-camera-p3768-fr_imx577-cam0-2lane-overlay.dtbo
dtbo-y += tegra234-p3767-camera-p3768-fr_imx577-cam1-2lane-overlay.dtbo
dtbo-y += tegra234-p3767-camera-p3768-fr_imx577-cam1-4lane-overlay.dtbo

dtbo-y += tegra234-p3767-camera-p3768-fr_imx585-cam0-2lane-overlay.dtbo
dtbo-y += tegra234-p3767-camera-p3768-fr_imx585-cam1-2lane-overlay.dtbo
dtbo-y += tegra234-p3767-camera-p3768-fr_imx585-cam1-4lane-overlay.dtbo

dtbo-y += tegra234-p3767-camera-p3768-fr_imx662-cam0-2lane-overlay.dtbo
dtbo-y += tegra234-p3767-camera-p3768-fr_imx662-cam1-2lane-overlay.dtbo
dtbo-y += tegra234-p3767-camera-p3768-fr_imx662-cam1-4lane-overlay.dtbo

dtbo-y += tegra234-p3767-camera-p3768-fr_imx675-cam0-2lane-overlay.dtbo
dtbo-y += tegra234-p3767-camera-p3768-fr_imx675-cam1-2lane-overlay.dtbo
dtbo-y += tegra234-p3767-camera-p3768-fr_imx675-cam1-4lane-overlay.dtbo

dtbo-y += tegra234-p3767-camera-p3768-fr_imx676-cam0-2lane-overlay.dtbo
dtbo-y += tegra234-p3767-camera-p3768-fr_imx676-cam1-2lane-overlay.dtbo
dtbo-y += tegra234-p3767-camera-p3768-fr_imx676-cam1-4lane-overlay.dtbo

dtbo-y += tegra234-p3767-camera-p3768-fr_imx678-cam0-2lane-overlay.dtbo
dtbo-y += tegra234-p3767-camera-p3768-fr_imx678-cam1-2lane-overlay.dtbo
dtbo-y += tegra234-p3767-camera-p3768-fr_imx678-cam1-4lane-overlay.dtbo

dtbo-y += tegra234-p3767-camera-p3768-fr_imx715-cam0-2lane-overlay.dtbo
dtbo-y += tegra234-p3767-camera-p3768-fr_imx715-cam1-2lane-overlay.dtbo
dtbo-y += tegra234-p3767-camera-p3768-fr_imx715-cam1-4lane-overlay.dtbo

dtbo-y += tegra234-p3767-camera-p3768-fr_imx900-cam0-1lane-overlay.dtbo
dtbo-y += tegra234-p3767-camera-p3768-fr_imx900-cam0-2lane-overlay.dtbo
dtbo-y += tegra234-p3767-camera-p3768-fr_imx900-cam1-1lane-overlay.dtbo
dtbo-y += tegra234-p3767-camera-p3768-fr_imx900-cam1-2lane-overlay.dtbo
dtbo-y += tegra234-p3767-camera-p3768-fr_imx900-cam1-4lane-overlay.dtbo

dtbo-y += tegra234-p3767-camera-p3768-fr_cam0-gmsl-overlay.dtbo
dtbo-y += tegra234-p3767-camera-p3768-fr_cam1-gmsl-overlay.dtbo

ifneq ($(dtb-y),)
dtb-y := $(addprefix $(makefile-path)/,$(dtb-y))
endif
ifneq ($(dtbo-y),)
dtbo-y := $(addprefix $(makefile-path)/,$(dtbo-y))
endif

dtb-y += $(old-dtb)
dtbo-y += $(old-dtbo)
